import type {
  BuilderNode,
  FeedItem,
  FounderProfileValues,
  InvestorCriteriaValues,
  InvestorDealStage,
  InvestorSignal,
  Meetup,
  NetworkCluster,
} from '@/lib/apparent-types';

export const investorDealStages: InvestorDealStage[] = ['New', 'Reviewing', 'Reached Out', 'Meeting', 'Watchlist'];

export const defaultInvestorCriteria: InvestorCriteriaValues = {
  thesis: '',
  sectors: '',
  stage: '',
  checkSize: '',
  geography: '',
  founderSignals: '',
  passSignals: '',
  portfolioExamples: '',
  publicProfileEnabled: 'false',
  publicFields: JSON.stringify(['thesis', 'sectors', 'stage', 'geography']),
};

export const defaultFounderProfile: FounderProfileValues = {
  profileName: '',
  headline: '',
  bio: '',
  profilePhotoUrl: '',
  currentBuild: '',
  category: '',
  stage: '',
  github: '',
  traction: '',
  lookingFor: '',
  location: '',
  press: '',
  website: '',
  linkedin: '',
  xProfile: '',
  pastProducts: '',
  fundraisingStatus: 'not_raising',
  raisingRound: '',
  raisingAmount: '',
  raisingAsk: '',
  openToContact: 'true',
};

export const seedInvestorSignals: InvestorSignal[] = [
  {
    id: 'seed-kerneltrace',
    company: 'KernelTrace',
    founder: 'Maya Chen',
    detail: 'GitHub-native analytics for engineering leaders. New repository activity, two design partners, and repeat weekly usage.',
    source: 'GitHub + launch post',
    sourceUrl: 'https://github.com/',
    profileUrl: '/profile/maya-chen',
    relevance: 96,
    freshness: '18 min ago',
    stage: 'Seed',
    location: 'Brooklyn',
    column: 'New',
    outreach: 'Maya, saw KernelTrace showing repeat usage from eng leads. Your GitHub proof lines up with our devtools thesis. Open to a quick chat this week?',
    sourceType: 'GitHub + launch post',
    freshnessAt: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
    githubUrl: 'https://github.com/',
    rawTags: ['devtools', 'analytics', 'github', 'seed'],
  },
  {
    id: 'seed-agentdock',
    company: 'AgentDock',
    founder: 'Arjun Patel',
    detail: 'Open-source agent deployment control plane with launch traction from infra-heavy teams and strong technical documentation.',
    source: 'Product launch + docs',
    sourceUrl: 'https://github.com/',
    profileUrl: '/profile/arjun-patel',
    relevance: 91,
    freshness: '41 min ago',
    stage: 'Pre-seed',
    location: 'San Francisco',
    column: 'Reviewing',
    outreach: 'Arjun, AgentDock hits a few things we look for: hard technical wedge, public proof, and infra buyer pull. Worth comparing notes?',
    sourceType: 'Product launch + docs',
    freshnessAt: new Date(Date.now() - 41 * 60 * 1000).toISOString(),
    githubUrl: 'https://github.com/',
    rawTags: ['infra', 'agents', 'open-source', 'pre-seed'],
  },
  {
    id: 'seed-helploop',
    company: 'HelpLoop AI',
    founder: 'Nora Ellis',
    detail: 'AI support automation with a public customer case study and visible hiring signal around implementation engineering.',
    source: 'Customer story',
    sourceUrl: 'https://example.com/customer-story',
    profileUrl: '/profile/nora-ellis',
    relevance: 88,
    freshness: '2h ago',
    stage: 'Seed',
    location: 'Seattle',
    column: 'Reached Out',
    outreach: 'Nora, the customer proof around HelpLoop stood out. We spend a lot of time on applied AI workflows and would like to learn more.',
    sourceType: 'Customer story',
    freshnessAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    githubUrl: '',
    rawTags: ['ai', 'support', 'automation', 'seed'],
  },
  {
    id: 'seed-schemapilot',
    company: 'SchemaPilot',
    founder: 'Elena Morris',
    detail: 'Database migration assistant showing fresh Hacker News attention, CLI usage, and a sharp wedge for platform teams.',
    source: 'HN + package installs',
    sourceUrl: 'https://news.ycombinator.com/',
    profileUrl: '/profile/elena-morris',
    relevance: 84,
    freshness: 'Today',
    stage: 'Pre-seed',
    location: 'Remote',
    column: 'Meeting',
    outreach: 'Elena, SchemaPilot is exactly the kind of boring-but-urgent infra workflow we like. Would be useful to hear what teams are pulling hardest.',
    sourceType: 'HN + package installs',
    freshnessAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    githubUrl: 'https://github.com/',
    rawTags: ['database', 'cli', 'infra', 'pre-seed'],
  },
  {
    id: 'seed-briefwise',
    company: 'Briefwise',
    founder: 'Samir Rao',
    detail: 'Workflow automation for legal ops with a fast-moving founder, early pilots, and narrow ICP clarity.',
    source: 'Founder profile',
    sourceUrl: 'https://example.com/briefwise',
    profileUrl: '/profile/samir-rao',
    relevance: 79,
    freshness: 'Yesterday',
    stage: 'Seed',
    location: 'Austin',
    column: 'Watchlist',
    outreach: 'Samir, Briefwise has a focused wedge and the pilot motion is interesting. We are tracking legal ops workflows and would like to stay close.',
    sourceType: 'Founder profile',
    freshnessAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    githubUrl: '',
    rawTags: ['workflow', 'legal-ops', 'automation', 'seed'],
  },
];

export const seedMeetups: Meetup[] = [
  {
    id: 'seed-meetup-sf-ai-infra',
    hostId: 'seed-investor',
    hostRole: 'investor',
    title: 'AI Infra Builder Office Hours',
    audience: 'Technical founders building deployment, evals, and observability tools.',
    city: 'San Francisco',
    venue: 'South Park Commons',
    startsAt: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    capacity: 32,
    description: 'Small room for founders with public proof and infra-heavy users.',
    attendeeCount: 18,
    isJoined: false,
  },
  {
    id: 'seed-meetup-ny-devtools',
    hostId: 'seed-investor',
    hostRole: 'investor',
    title: 'Devtools Demo Night',
    audience: 'Builders shipping developer workflows with active GitHub or package signals.',
    city: 'New York',
    venue: 'Union Square Loft',
    startsAt: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString(),
    capacity: 45,
    description: 'Demo-format meetup with investor follow-up slots after each product walkthrough.',
    attendeeCount: 27,
    isJoined: false,
  },
];

export const cityCoordinates: Record<string, Pick<NetworkCluster, 'x' | 'y'>> = {
  'San Francisco': { x: 18, y: 54 },
  Brooklyn: { x: 72, y: 45 },
  'New York': { x: 75, y: 43 },
  Seattle: { x: 22, y: 25 },
  Austin: { x: 54, y: 70 },
  Remote: { x: 48, y: 42 },
};

export const cityGeoCoordinates: Record<string, { latitude: number; longitude: number }> = {
  'San Francisco': { latitude: 37.7749, longitude: -122.4194 },
  Brooklyn: { latitude: 40.6782, longitude: -73.9442 },
  'New York': { latitude: 40.7128, longitude: -74.006 },
  Seattle: { latitude: 47.6062, longitude: -122.3321 },
  Austin: { latitude: 30.2672, longitude: -97.7431 },
  Boston: { latitude: 42.3601, longitude: -71.0589 },
  Chicago: { latitude: 41.8781, longitude: -87.6298 },
  'Los Angeles': { latitude: 34.0522, longitude: -118.2437 },
  Miami: { latitude: 25.7617, longitude: -80.1918 },
  Denver: { latitude: 39.7392, longitude: -104.9903 },
  Atlanta: { latitude: 33.749, longitude: -84.388 },
  Toronto: { latitude: 43.6532, longitude: -79.3832 },
  London: { latitude: 51.5072, longitude: -0.1276 },
  Paris: { latitude: 48.8566, longitude: 2.3522 },
  Berlin: { latitude: 52.52, longitude: 13.405 },
  Amsterdam: { latitude: 52.3676, longitude: 4.9041 },
  Stockholm: { latitude: 59.3293, longitude: 18.0686 },
  Singapore: { latitude: 1.3521, longitude: 103.8198 },
  Bengaluru: { latitude: 12.9716, longitude: 77.5946 },
  Mumbai: { latitude: 19.076, longitude: 72.8777 },
  Delhi: { latitude: 28.6139, longitude: 77.209 },
  Hyderabad: { latitude: 17.385, longitude: 78.4867 },
  Pune: { latitude: 18.5204, longitude: 73.8567 },
  'Tel Aviv': { latitude: 32.0853, longitude: 34.7818 },
  Dubai: { latitude: 25.2048, longitude: 55.2708 },
  Remote: { latitude: 39.8283, longitude: -98.5795 },
};

export const seedBuilderNodes: BuilderNode[] = [
  {
    id: 'seed-founder-maya-chen',
    founderId: 'seed-founder-maya-chen',
    founderName: 'Maya Chen',
    company: 'KernelTrace',
    displayLabel: 'KernelTrace',
    buildSummary:
      'GitHub-native analytics for engineering leaders with repeat weekly usage and two active design partners.',
    category: 'Devtools',
    stage: 'Seed',
    location: 'Brooklyn',
    latitude: cityGeoCoordinates.Brooklyn.latitude,
    longitude: cityGeoCoordinates.Brooklyn.longitude,
    proofLinks: [
      { label: 'GitHub', url: 'https://github.com/', type: 'github' },
      { label: 'Profile', url: '/profile/maya-chen', type: 'profile' },
    ],
    traction: 'Repeat weekly usage, active GitHub signal, two design partners.',
    launchCount: 1,
    latestActivity: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
    latestActivityLabel: '18 min ago',
    fitScore: 90,
    matchReasons: ['GitHub proof', 'Developer workflow', 'Fresh launch'],
    profileUrl: '/profile/maya-chen',
    githubUrl: 'https://github.com/',
    pressUrl: '',
    launchUrl: 'https://github.com/',
    rawTags: ['devtools', 'analytics', 'github', 'seed'],
  },
  {
    id: 'seed-founder-arjun-patel',
    founderId: 'seed-founder-arjun-patel',
    founderName: 'Arjun Patel',
    company: 'AgentDock',
    displayLabel: 'AgentDock',
    buildSummary:
      'Open-source agent deployment control plane with infra-heavy launch traction and strong technical documentation.',
    category: 'AI infra',
    stage: 'Pre-seed',
    location: 'San Francisco',
    latitude: cityGeoCoordinates['San Francisco'].latitude,
    longitude: cityGeoCoordinates['San Francisco'].longitude,
    proofLinks: [
      { label: 'GitHub', url: 'https://github.com/', type: 'github' },
      { label: 'Launch', url: 'https://github.com/', type: 'launch' },
    ],
    traction: 'Open-source launch traction from infrastructure teams.',
    launchCount: 1,
    latestActivity: new Date(Date.now() - 41 * 60 * 1000).toISOString(),
    latestActivityLabel: '41 min ago',
    fitScore: 88,
    matchReasons: ['Open-source proof', 'AI infra', 'Technical founder'],
    profileUrl: '/profile/arjun-patel',
    githubUrl: 'https://github.com/',
    pressUrl: '',
    launchUrl: 'https://github.com/',
    rawTags: ['infra', 'agents', 'open-source', 'pre-seed'],
  },
  {
    id: 'seed-founder-nora-ellis',
    founderId: 'seed-founder-nora-ellis',
    founderName: 'Nora Ellis',
    company: 'HelpLoop AI',
    displayLabel: 'HelpLoop AI',
    buildSummary:
      'AI support automation with a public customer story and implementation engineering hiring signal.',
    category: 'AI SaaS',
    stage: 'Seed',
    location: 'Seattle',
    latitude: cityGeoCoordinates.Seattle.latitude,
    longitude: cityGeoCoordinates.Seattle.longitude,
    proofLinks: [
      { label: 'Customer story', url: 'https://example.com/customer-story', type: 'proof' },
      { label: 'Profile', url: '/profile/nora-ellis', type: 'profile' },
    ],
    traction: 'Public customer case study and active implementation pull.',
    launchCount: 1,
    latestActivity: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    latestActivityLabel: '2h ago',
    fitScore: 82,
    matchReasons: ['Customer proof', 'AI workflow', 'Hiring signal'],
    profileUrl: '/profile/nora-ellis',
    githubUrl: '',
    pressUrl: 'https://example.com/customer-story',
    launchUrl: '',
    rawTags: ['ai', 'support', 'automation', 'seed'],
  },
  {
    id: 'seed-founder-elena-morris',
    founderId: 'seed-founder-elena-morris',
    founderName: 'Elena Morris',
    company: 'SchemaPilot',
    displayLabel: 'SchemaPilot',
    buildSummary:
      'Database migration assistant with fresh developer attention, CLI usage, and a platform-team wedge.',
    category: 'Developer infrastructure',
    stage: 'Pre-seed',
    location: 'Remote',
    latitude: cityGeoCoordinates.Remote.latitude,
    longitude: cityGeoCoordinates.Remote.longitude,
    proofLinks: [
      { label: 'GitHub', url: 'https://github.com/', type: 'github' },
      { label: 'HN thread', url: 'https://news.ycombinator.com/', type: 'press' },
    ],
    traction: 'Fresh developer attention and CLI usage from platform teams.',
    launchCount: 1,
    latestActivity: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    latestActivityLabel: 'Yesterday',
    fitScore: 78,
    matchReasons: ['Developer attention', 'CLI usage', 'Infra wedge'],
    profileUrl: '/profile/elena-morris',
    githubUrl: 'https://github.com/',
    pressUrl: 'https://news.ycombinator.com/',
    launchUrl: 'https://github.com/',
    rawTags: ['database', 'cli', 'infra', 'pre-seed'],
  },
  {
    id: 'seed-founder-samir-rao',
    founderId: 'seed-founder-samir-rao',
    founderName: 'Samir Rao',
    company: 'Briefwise',
    displayLabel: 'Briefwise',
    buildSummary:
      'Workflow automation for legal ops with early pilots, a focused ICP, and a fast-moving product cadence.',
    category: 'Workflow automation',
    stage: 'Seed',
    location: 'Austin',
    latitude: cityGeoCoordinates.Austin.latitude,
    longitude: cityGeoCoordinates.Austin.longitude,
    proofLinks: [
      { label: 'Profile', url: 'https://example.com/briefwise', type: 'profile' },
    ],
    traction: 'Early pilots and narrow ICP clarity in legal operations.',
    launchCount: 1,
    latestActivity: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
    latestActivityLabel: 'Yesterday',
    fitScore: 74,
    matchReasons: ['Early pilots', 'Narrow ICP', 'Workflow wedge'],
    profileUrl: '/profile/samir-rao',
    githubUrl: '',
    pressUrl: '',
    launchUrl: 'https://example.com/briefwise',
    rawTags: ['workflow', 'legal-ops', 'automation', 'seed'],
  },
];

export const generalFeedDefaults: FeedItem[] = [
  {
    id: 'front-ai-infra-workflows',
    title: 'AI infra companies are moving from demos to durable workflows',
    detail: 'The strongest launches this week are selling reliability, evals, observability, and deployment confidence.',
    tag: 'Market signal',
    source: 'Front page',
    actor: 'Apparent Radar',
    meta: '12 min ago',
    saved: false,
    reposted: false,
    reply: '',
  },
  {
    id: 'front-devtools-usage',
    title: 'Developer tools are getting evaluated by usage quality, not waitlists',
    detail: 'Investors are paying closer attention to repeat CLI/API usage, GitHub activity, and team expansion signals.',
    tag: 'VC pattern',
    source: 'Front page',
    actor: 'Capital Notes',
    meta: '28 min ago',
    saved: false,
    reposted: false,
    reply: '',
  },
  {
    id: 'front-founder-meetups',
    title: 'Founder meetups are clustering around applied AI, devtools, and vertical SaaS',
    detail: 'Smaller rooms with specific theses are outperforming broad networking events for useful introductions.',
    tag: 'Meetups',
    source: 'Front page',
    actor: 'Builder Rooms',
    meta: '1h ago',
    saved: false,
    reposted: false,
    reply: '',
  },
];
